apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hw-dumper
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: hw-dumper
            image: nandanrao/hw-dumper
            resources:
              requests:
                memory: "500Mi"
            envFrom:
            - secretRef:
                name: hw-dumper-envs
